// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "description for product 1",
                            Name = "product 1",
                            Price = 123m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "description for product 2",
                            Name = "product 2",
                            Price = 517m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "description for product 3",
                            Name = "product 3",
                            Price = 461m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "description for product 4",
                            Name = "product 4",
                            Price = 868m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "description for product 5",
                            Name = "product 5",
                            Price = 297m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "description for product 6",
                            Name = "product 6",
                            Price = 618m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "description for product 7",
                            Name = "product 7",
                            Price = 668m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "description for product 8",
                            Name = "product 8",
                            Price = 520m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "description for product 9",
                            Name = "product 9",
                            Price = 770m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "description for product 10",
                            Name = "product 10",
                            Price = 590m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "description for product 11",
                            Name = "product 11",
                            Price = 549m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "description for product 12",
                            Name = "product 12",
                            Price = 355m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "description for product 13",
                            Name = "product 13",
                            Price = 632m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "description for product 14",
                            Name = "product 14",
                            Price = 179m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "description for product 15",
                            Name = "product 15",
                            Price = 559m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "description for product 16",
                            Name = "product 16",
                            Price = 869m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "description for product 17",
                            Name = "product 17",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "description for product 18",
                            Name = "product 18",
                            Price = 545m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "description for product 19",
                            Name = "product 19",
                            Price = 710m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "description for product 20",
                            Name = "product 20",
                            Price = 790m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "description for product 21",
                            Name = "product 21",
                            Price = 604m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "description for product 22",
                            Name = "product 22",
                            Price = 363m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "description for product 23",
                            Name = "product 23",
                            Price = 964m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "description for product 24",
                            Name = "product 24",
                            Price = 361m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "description for product 25",
                            Name = "product 25",
                            Price = 748m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "description for product 26",
                            Name = "product 26",
                            Price = 478m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "description for product 27",
                            Name = "product 27",
                            Price = 482m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "description for product 28",
                            Name = "product 28",
                            Price = 219m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "description for product 29",
                            Name = "product 29",
                            Price = 462m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "description for product 30",
                            Name = "product 30",
                            Price = 787m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "description for product 31",
                            Name = "product 31",
                            Price = 217m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "description for product 32",
                            Name = "product 32",
                            Price = 764m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "description for product 33",
                            Name = "product 33",
                            Price = 640m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "description for product 34",
                            Name = "product 34",
                            Price = 444m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "description for product 35",
                            Name = "product 35",
                            Price = 103m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "description for product 36",
                            Name = "product 36",
                            Price = 408m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "description for product 37",
                            Name = "product 37",
                            Price = 407m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "description for product 38",
                            Name = "product 38",
                            Price = 697m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "description for product 39",
                            Name = "product 39",
                            Price = 685m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "description for product 40",
                            Name = "product 40",
                            Price = 777m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "description for product 41",
                            Name = "product 41",
                            Price = 717m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "description for product 42",
                            Name = "product 42",
                            Price = 591m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "description for product 43",
                            Name = "product 43",
                            Price = 514m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "description for product 44",
                            Name = "product 44",
                            Price = 759m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "description for product 45",
                            Name = "product 45",
                            Price = 970m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "description for product 46",
                            Name = "product 46",
                            Price = 595m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "description for product 47",
                            Name = "product 47",
                            Price = 980m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "description for product 48",
                            Name = "product 48",
                            Price = 164m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "description for product 49",
                            Name = "product 49",
                            Price = 701m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "description for product 50",
                            Name = "product 50",
                            Price = 321m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "description for product 51",
                            Name = "product 51",
                            Price = 780m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "description for product 52",
                            Name = "product 52",
                            Price = 119m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "description for product 53",
                            Name = "product 53",
                            Price = 619m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "description for product 54",
                            Name = "product 54",
                            Price = 686m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "description for product 55",
                            Name = "product 55",
                            Price = 356m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "description for product 56",
                            Name = "product 56",
                            Price = 722m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "description for product 57",
                            Name = "product 57",
                            Price = 600m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "description for product 58",
                            Name = "product 58",
                            Price = 776m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "description for product 59",
                            Name = "product 59",
                            Price = 781m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "description for product 60",
                            Name = "product 60",
                            Price = 475m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "description for product 61",
                            Name = "product 61",
                            Price = 177m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "description for product 62",
                            Name = "product 62",
                            Price = 504m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "description for product 63",
                            Name = "product 63",
                            Price = 458m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "description for product 64",
                            Name = "product 64",
                            Price = 296m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "description for product 65",
                            Name = "product 65",
                            Price = 607m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "description for product 66",
                            Name = "product 66",
                            Price = 341m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "description for product 67",
                            Name = "product 67",
                            Price = 568m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "description for product 68",
                            Name = "product 68",
                            Price = 510m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "description for product 69",
                            Name = "product 69",
                            Price = 382m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "description for product 70",
                            Name = "product 70",
                            Price = 622m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "description for product 71",
                            Name = "product 71",
                            Price = 925m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "description for product 72",
                            Name = "product 72",
                            Price = 798m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "description for product 73",
                            Name = "product 73",
                            Price = 714m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "description for product 74",
                            Name = "product 74",
                            Price = 364m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "description for product 75",
                            Name = "product 75",
                            Price = 948m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "description for product 76",
                            Name = "product 76",
                            Price = 347m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "description for product 77",
                            Name = "product 77",
                            Price = 267m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "description for product 78",
                            Name = "product 78",
                            Price = 531m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "description for product 79",
                            Name = "product 79",
                            Price = 526m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "description for product 80",
                            Name = "product 80",
                            Price = 340m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "description for product 81",
                            Name = "product 81",
                            Price = 349m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "description for product 82",
                            Name = "product 82",
                            Price = 362m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "description for product 83",
                            Name = "product 83",
                            Price = 147m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "description for product 84",
                            Name = "product 84",
                            Price = 300m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "description for product 85",
                            Name = "product 85",
                            Price = 133m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "description for product 86",
                            Name = "product 86",
                            Price = 391m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "description for product 87",
                            Name = "product 87",
                            Price = 718m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "description for product 88",
                            Name = "product 88",
                            Price = 248m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "description for product 89",
                            Name = "product 89",
                            Price = 852m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "description for product 90",
                            Name = "product 90",
                            Price = 379m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "description for product 91",
                            Name = "product 91",
                            Price = 772m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "description for product 92",
                            Name = "product 92",
                            Price = 495m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "description for product 93",
                            Name = "product 93",
                            Price = 828m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "description for product 94",
                            Name = "product 94",
                            Price = 773m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "description for product 95",
                            Name = "product 95",
                            Price = 652m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "description for product 96",
                            Name = "product 96",
                            Price = 620m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "description for product 97",
                            Name = "product 97",
                            Price = 382m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "description for product 98",
                            Name = "product 98",
                            Price = 298m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "description for product 99",
                            Name = "product 99",
                            Price = 983m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "description for product 100",
                            Name = "product 100",
                            Price = 306m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductInStockId"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 67
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 59
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 58
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 73
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 77
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 58
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 68
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 71
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 78
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 34
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 92
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 95
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 41
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 51
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 81
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 69
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 75
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 50
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 47
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 88
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
